import { useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import './About.css';

const About = () => {
  useEffect(() => { document.title = 'About — QuizApp'; }, []);

  return (
    <div className="about-container">
      <Sidebar />
      <div className="about-content">
        <div className="about-header">
          <h1>About QuizApp</h1>
          <p className="about-tagline">Create, share, and take quizzes — powered by AI</p>
        </div>

        <section className="about-section">
          <h2>🚀 What is QuizApp?</h2>
          <p>
            QuizApp is a full-stack quiz platform that lets you create quizzes manually
            or generate them instantly using AI. Share your quizzes with the community,
            challenge yourself, and track your progress over time.
          </p>
        </section>

        <section className="about-section">
          <h2>✨ Key Features</h2>
          <ul className="feature-list">
            <li><strong>AI Quiz Generation</strong> — Describe a topic and get a quiz generated by Google Gemini</li>
            <li><strong>Manual Quiz Builder</strong> — Create quizzes with a drag-and-drop-style editor</li>
            <li><strong>Import &amp; Export</strong> — Import quizzes from JSON files or export yours to share</li>
            <li><strong>Server-Side Scoring</strong> — Answers are validated on the server for fairness</li>
            <li><strong>Leaderboards</strong> — Per-quiz and global leaderboards to compete with others</li>
            <li><strong>Detailed Statistics</strong> — Track your score history, category breakdown, and trends</li>
            <li><strong>Attempt Review</strong> — Go back and review each question after finishing a quiz</li>
          </ul>
        </section>

        <section className="about-section">
          <h2>❓ FAQ</h2>
          <div className="faq-list">
            <details className="faq-item">
              <summary>How do I create a quiz?</summary>
              <p>
                Go to <strong>Create Quiz</strong> from the sidebar. You can type questions
                manually, generate them with AI by entering a topic, or import a JSON file.
              </p>
            </details>
            <details className="faq-item">
              <summary>How is scoring calculated?</summary>
              <p>
                Scoring is done server-side. When you submit your answers, the server compares
                them to the correct answers and calculates the percentage. This prevents
                any client-side manipulation.
              </p>
            </details>
            <details className="faq-item">
              <summary>Can I edit a quiz after publishing it?</summary>
              <p>
                Yes! As the quiz author you can edit the title, description, questions, and
                settings at any time from your <strong>My Quizzes</strong> page.
              </p>
            </details>
            <details className="faq-item">
              <summary>How do leaderboards work?</summary>
              <p>
                Each quiz has its own leaderboard showing top scores. There is also a global
                leaderboard aggregating performance across all quizzes.
              </p>
            </details>
            <details className="faq-item">
              <summary>Is my data safe?</summary>
              <p>
                Passwords are hashed using bcrypt before storage. Authentication uses
                short-lived JWT tokens. All API endpoints are rate-limited to prevent abuse.
              </p>
            </details>
            <details className="faq-item">
              <summary>Can I delete my account?</summary>
              <p>
                Yes. Go to <strong>Settings</strong> and use the "Delete Account" option.
                You can choose to keep or remove your published quizzes.
              </p>
            </details>
          </div>
        </section>

        <section className="about-section">
          <h2>🛠️ Tech Stack</h2>
          <div className="tech-grid">
            <div className="tech-item">
              <span className="tech-label">Frontend</span>
              <span className="tech-value">React 19, Redux Toolkit, Vite</span>
            </div>
            <div className="tech-item">
              <span className="tech-label">Backend</span>
              <span className="tech-value">FastAPI, Python 3.12</span>
            </div>
            <div className="tech-item">
              <span className="tech-label">Database</span>
              <span className="tech-value">MongoDB</span>
            </div>
            <div className="tech-item">
              <span className="tech-label">AI</span>
              <span className="tech-value">Google Gemini</span>
            </div>
          </div>
        </section>

        <section className="about-section">
          <h2>📬 Contact &amp; Feedback</h2>
          <p>
            Found a bug or have a feature idea? Open an issue on the project repository
            or reach out via the channels described in the project README.
          </p>
        </section>

        <footer className="about-footer">
          <p>QuizApp &copy; {new Date().getFullYear()}</p>
        </footer>
      </div>
    </div>
  );
};

export default About;
